<?php

const DB_HOSTNAME = '127.0.0.1';
const DB_USERNAME = 'bulat';
const DB_PASSWORD = '1';
const DB_DBNAME = 'testdb';
const DB_CHARSET = 'utf8';

const DB_ERROR_NOERROR = '0';
const DB_ERROR_CREATE_RECORD_UC_VIOLATION = '23000';
const DB_ERROR_CREATE_RECORD_EMPTY_FIELDS = '23001';
const DB_ERROR_UPDATE_RECORD_NO_ID = '23002';
const DB_ERROR_UNKNOWN_CREATE_RECORD = '23003';
const DB_ERROR_UPDATE_RECORD_DOESNT_EXIST = '23004';
const DB_ERROR_RECORD_DOCNUM_ALREADY_EXISTS = '23005';
